POST http://localhost:5000/signup
Content-Type: application/json

{
    "username" : "Sayantan",
    "email" : "sssamanta789@gmail.com",
    "password" : "Jake2189"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "sssamanta789@gmail.com",
    "password" : "Jake2189"
}
###

POST http://localhost:5000/logout

###

GET  http://localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODE3ZjBlZjEwMWY5YzUwMDA4NDMzOCIsImlhdCI6MTYxOTEwNzExMiwiZXhwIjoxNjE5MTEwNzEyLCJpc3MiOiJzYXlhbnRhbi5jb20ifQ.AHzh4nuf2JrRkRusNL1FBFAYZnqlwzy_46E7q3D9Xps

