POST http://localhost:5000/signup
Content-Type: application/json

{
    "username" : "Sayantan",
    "email" : "sssamanta789@gmail.com",
    "password" : "Jake2189"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "sssamanta789@gmail.com",
    "password" : "Jake2189"
}
###
POST http://localhost:5000/refresh
Content-Type: application/json

{
   "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODJlNjM0MWY5MTRkYzE4OWRkZjRjYyIsImlhdCI6MTYxOTE5MTM0OSwiZXhwIjoxNjUwNzQ4OTQ5LCJpc3MiOiJzYXlhbnRhbi5jb20ifQ.zqt-1_HMvNTZSXYaONl_Q05k9hFWeTJGXPI2xqk5hwE"
}
###
POST http://localhost:5000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODJlNzExMWY5MTRkYzE4OWRkZjRjZiIsImlhdCI6MTYxOTE5MzEzMSwiZXhwIjoxNjE5MTk0MDMxLCJpc3MiOiJzYXlhbnRhbi5jb20ifQ.b0nAOW3mR1R5wgUYRKlNcpc1hQX715xiEB7ANfBj1m0


Content-Type: application/json
{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODJlNzExMWY5MTRkYzE4OWRkZjRjZiIsImlhdCI6MTYxOTE5MzEzMSwiZXhwIjoxNjUwNzUwNzMxLCJpc3MiOiJzYXlhbnRhbi5jb20ifQ.ORTNf97BYps6gDrvALQmHz1DrVziWdyEnVSUGU8uvVI"
}



###

GET  http://localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODI3MmQ0NzUyODY0MzdlODM3NTE0YyIsImlhdCI6MTYxOTE2Mzg5NiwiZXhwIjoxNjE5MTY0Nzk2LCJpc3MiOiJzYXlhbnRhbi5jb20ifQ.zd7692mInRIOQJJ9OPOJeX_EZIfDuFxbxk3RwrZU0g8
