### CHECK INDEX

GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTg2NTIxNjEsImV4cCI6MTYxODY1NTc2MSwiYXVkIjoiNjA3OWM5MTVhM2U5ZDAzYTAzNjA1YmQ0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.fWk-4YGW0f1E6O-81DPGlGyceIn5j2GZQAMqODDvB14

### SIGNUP ROUTE

POST http://localhost:3000/register
Content-Type: application/json

{   
    "name" : "Urban Example",
    "email" : "urbanui@google.com",
    "password" : "Sammyboi"
}


### LOGIN ROUTE

POST http://localhost:3000/login
Content-Type: application/json

{
   "email" : "sssamanta@google.com",
   "password" : "Sayantan"
}


### REFRESH TOKEN ROUTE

POST http://localhost:3000/refresh-token


### LOGOUT ROUTE

POST http://localhost:3000/logout
